protected/models/Link.php
<?php



/**
 * This is the model class for table "link".
 *
 * The followings are the available columns in table 'link':
 * @property integer $id
 * @property string $title
 * @property string $url
 * @property integer $link_category_id
 * @property string $image
 * @property integer $order
 * @property string $time_created
 */

class Link extends CActiveRecord

{

	/**
	 * @return string the associated database table name
	 */

	public function tableName()

	{

		return 'link';

	}



	/**
	 * @return array validation rules for model attributes.
	 */

	public function rules()

	{

		// NOTE: you should only define rules for those attributes that

		// will receive user inputs.

		return array(

			array('title', 'required'),

			array('link_category_id, order, new_tab', 'numerical', 'integerOnly'=>true),

			array('title, url, image', 'length', 'max'=>255),

			array('time_created', 'safe'),

			// The following rule is used by search().

			// @todo Please remove those attributes that should not be searched.

			array('id, title, url, link_category_id, image, order, time_created', 'safe', 'on'=>'search'),

		);

	}



	/**
	 * @return array relational rules.
	 */

	public function relations()

	{

		// NOTE: you may need to adjust the relation name and the related

		// class name for the relations automatically generated below.

		return array(

			'LinkCategory'=>array(self::BELONGS_TO,'LinkCategory','link_category_id'),

		);

	}



	/**
	 * @return array customized attribute labels (name=>label)
	 */

	public function attributeLabels()

	{

		return array(

			'id' => 'ID',

			'title' => 'Title',

			'url' => 'Url',

			'link_category_id' => 'Category',

			'image' => 'Image',

			'order' => 'Order',

			'time_created' => 'Time Created',

			'new_tab' => 'Open in New Tab'

		);

	}



	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */

	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('url',$this->url,true);
		$criteria->compare('link_category_id',$this->link_category_id);
		$criteria->compare('image',$this->image,true);
		$criteria->compare('order',$this->order);
		$criteria->compare('time_created',$this->time_created,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));

	}



	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Link the static model class
	 */

	public static function model($className=__CLASS__)

	{

		return parent::model($className);

	}

	

	public function getLink($link_category_id)

	{	

		return Link::model()->findAllByAttributes(array('link_category_id'=>$link_category_id),array('order'=>'t.order ASC'));			

	}

	

	public function getBackendThumbnail($data,$class)

	{

		if($data!='')

			return CHtml::image(Yii::app()->theme->baseUrl.'/uploads/link/'.$data,'',array('class'=>$class));

		else

			return CHtml::image(Yii::app()->theme->baseUrl.'/images/image_not_found.gif','',array('class'=>'admin-photo'));

	}

	

	public function getImage($htmlOptions=array())

	{

		return CHtml::image(Yii::app()->theme->baseUrl.'/uploads/link/'.$this->image,'',$htmlOptions);

	}

	

	public function getUrl()

	{

		return $this->url;

	}

	

	protected function beforeDelete()

	{

		$path = Yii::app()->theme->basePath.'/uploads/link/';

		if(file_exists($path.$this->image) AND $this->image!= '')

			unlink($path.$this->image);

			

		return true;

	}

	

	public function getRelationField($relation,$field)

	{

		if(!empty($this->$relation->$field))

			return $this->$relation->$field;

		else

			return null;

	}

}

protected/controllers/LinkController.php
<?php

class LinkController extends Controller
{
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/admin/column2';

/**
* @return array action filters
*/
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

/**
* Specifies the access control rules.
* This method is used by the 'accessControl' filter.
* @return array access control rules
*/
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','view'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

/**
* Displays a particular model.
* @param integer $id the ID of the model to be displayed
*/
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

/**
* Creates a new model.
* If creation is successful, the browser will be redirected to the 'view' page.
*/
	public function actionCreate()
	{
		$model=new Link;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Link']))
		{
			$model->attributes=$_POST['Link'];
			date_default_timezone_set('Asia/Jakarta');
			$model->time_created = date('Y-m-d H:i:s');
			$image = CUploadedFile::getInstance($model,'image');
			
			if($image!==null)
				$model->image = str_replace(' ','-',time().'_'.$image->name);
			
			if($model->save())
			{
				if($image!==null)
				{
					$path = Yii::app()->theme->basePath.'/uploads/link/';
					$image->saveAs($path.$model->image);
				}
				
				Yii::app()->user->setFlash('success','Data berhasil ditambahkan');
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		$oldFile = $model->image;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Link']))
		{
			$model->attributes=$_POST['Link'];
			
			$image = CUploadedFile::getInstance($model,'image');
			
			if($image!==null)
				$model->image = str_replace(' ','-',time().'_'.$image->name);
			else
				$model->image = $oldFile;
			
			if($model->save())
			{
				if($image!==null)
				{
					$path = Yii::app()->theme->basePath.'/uploads/link/';
					$image->saveAs($path.$model->image);
				
					if(file_exists($path.$oldFile) AND $oldFile!='')
						unlink($path.$oldFile);
				}
				
				Yii::app()->user->setFlash('success','Data berhasil ditambahkan');
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
	public function actionDelete($id)
	{
		$model=$this->loadModel($id);
		if(Yii::app()->request->isPostRequest)
		{
			$this->loadModel($id)->delete();
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) 
                ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,
                        'Invalid request. Please do not repeat this request again.');
	}

/**
* Lists all models.
*/
public function actionIndex()
{
$dataProvider=new CActiveDataProvider('Link');
$this->render('index',array(
'dataProvider'=>$dataProvider,
));
}

/**
* Manages all models.
*/
	public function actionAdmin()
	{
		$model=new Link('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Link']))
			$model->attributes=$_GET['Link'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
$model=Link::model()->findByPk($id);
if($model===null)
throw new CHttpException(404,'The requested page does not exist.');
return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
if(isset($_POST['ajax']) && $_POST['ajax']==='link-form')
{
echo CActiveForm::validate($model);
Yii::app()->end();
}
}
}

protected/views/link/_form.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(

	'id'=>'link-form',

	'enableAjaxValidation'=>false,

	'htmlOptions'=>array('enctype'=>'multipart/form-data')

)); ?>



<p class="help-block">Fields with <span class="required">*</span> are required.</p>



<?php echo $form->errorSummary($model); ?>



	<?php echo $form->textFieldGroup($model,'title',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

	

	<?php echo $form->textFieldGroup($model,'url',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

	

	<?php echo $form->dropDownListGroup($model,'link_category_id',array('widgetOptions'=>array('data'=>CHtml::listData(LinkCategory::model()->findAll(),'id','title'),'htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>



	<?php echo $form->textFieldGroup($model,'order',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

	<?php echo $form->checkBoxGroup($model,'new_tab',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

	<?php echo $form->labelEx($model,'image',array('label'=>'Gambar Maksimal 200 KB')); ?>

	<?php if($model->image!='') { ?>

	<?php print CHTml::image(Yii::app()->request->baseUrl.'/uploads/link/'.$model->image."","",array("class"=>"")); ?>

	<?php } ?>

	<?php echo $form->fileField($model,'image'); ?>

	<?php echo $form->error($model,'image'); ?>

	

	<div>&nbsp;</div>

	

	<div class="form-actions well">

	<?php $this->widget('booster.widgets.TbButton', array(

			'buttonType'=>'submit',

			'context'=>'primary',

			'icon'=>'ok',

			'label'=>$model->isNewRecord ? 'Add' : 'Update',

		)); ?>

	</div>



<?php $this->endWidget(); ?>

protected/views/link/_search.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

		<?php echo $form->textFieldGroup($model,'id',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'title',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

		<?php echo $form->textFieldGroup($model,'url',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

		<?php echo $form->textFieldGroup($model,'link_category_id',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'image',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

		<?php echo $form->textFieldGroup($model,'order',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'created_time',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

	<div class="form-actions">
		<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType' => 'submit',
			'context'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/link/_view.php
<div class="view">

		<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('title')); ?>:</b>
	<?php echo CHtml::encode($data->title); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('url')); ?>:</b>
	<?php echo CHtml::encode($data->url); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('link_category_id')); ?>:</b>
	<?php echo CHtml::encode($data->link_category_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('image')); ?>:</b>
	<?php echo CHtml::encode($data->image); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('order')); ?>:</b>
	<?php echo CHtml::encode($data->order); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('created_time')); ?>:</b>
	<?php echo CHtml::encode($data->created_time); ?>
	<br />


</div>

protected/views/link/admin.php
<?php $this->breadcrumbs=array(
	'Link'=>array('admin'),
	'Kelola',
); ?>

<h1>Kelola Link</h1>

<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Add Link',
		'icon'=>'plus',
		'context'=>'primary',
		'url'=>array('link/create')
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Category',
		'icon'=>'list',
		'context'=>'primary',
		'url'=>array('linkCategory/admin')
)); ?>

<?php $this->widget('booster.widgets.TbGridView',array(
		'id'=>'link-grid',
		'type'=>'striped bordered',
		'dataProvider'=>$model->search(),
		'ajaxUpdate'=>false,
		'filter'=>$model,
		'columns'=>array(
			array(
				'header'=>'No',
				'value'=>'$this->grid->dataProvider->pagination->currentPage*$this->grid->dataProvider->pagination->pageSize+$row+1',
				'headerHtmlOptions'=>array('width'=>'5%','style'=>'text-align:center'),
				'htmlOptions'=>array('style'=>'text-align:center'),
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'title',
				'value'=>'$data->title',
				'headerHtmlOptions'=>array('width'=>'30%','style'=>'text-align:center'),
				'htmlOptions'=>array()
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'order',
				'value'=>'$data->order',
				'headerHtmlOptions'=>array('width'=>'5%','style'=>'text-align:center'),
				'htmlOptions'=>array('style'=>'text-align:center')
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'url',
				'value'=>'$data->url',
				'headerHtmlOptions'=>array('width'=>'15%','style'=>'text-align:center'),
				'htmlOptions'=>array('style'=>'text-align:center')
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'image',
				'type'=>'raw',
				'value'=>'Link::model()->getBackendThumbnail($data->image,"")',
				'headerHtmlOptions'=>array('width'=>'20%','style'=>'text-align:center'),
				'htmlOptions'=>array('style'=>'text-align:center')
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'link_category_id',
				'value'=>'$data->getRelationField("LinkCategory","title")',
				'filter'=>CHtml::listData(LinkCategory::model()->findAll(),'id','title'),
				'headerHtmlOptions'=>array('width'=>'15%','style'=>'text-align:center'),
				'htmlOptions'=>array('style'=>'text-align:center')
			),
			
			array(
				'class'=>'booster.widgets.TbButtonColumn',
				'headerHtmlOptions'=>array('width'=>'10%')
			),
		),
)); ?>

protected/views/link/create.php
<?php
$this->breadcrumbs=array(
	'Links'=>array('index'),
	'Create',
);

$this->menu=array(
array('label'=>'List Link','url'=>array('index')),
array('label'=>'Manage Link','url'=>array('admin')),
);
?>

<h1>Add Link</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/link/index.php
<?php
$this->breadcrumbs=array(
	'Links',
);

$this->menu=array(
array('label'=>'Create Link','url'=>array('create')),
array('label'=>'Manage Link','url'=>array('admin')),
);
?>

<h1>Links</h1>

<?php $this->widget('booster.widgets.TbListView',array(
'dataProvider'=>$dataProvider,
'itemView'=>'_view',
)); ?>

protected/views/link/update.php
<?php
$this->breadcrumbs=array(
	'Links'=>array('index'),
	$model->title=>array('view','id'=>$model->id),
	'Update',
);?>

	<h1>Update Link</h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/link/view.php
<?php
$this->breadcrumbs=array(
	'Links'=>array('index'),
	$model->title,
);?>

<h1>View Link</h1>

<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Update',
		'icon'=>'pencil',
		'context'=>'primary',
		'url'=>array('link/update','id'=>$model->id)
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Add',
		'context'=>'primary',
		'icon'=>'plus white',
		'url'=>array('/link/create')
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Manage',
		'context'=>'primary',
		'icon'=>'list white',
		'url'=>array('/link/admin')
)); ?>
<div>&nbsp;</div>

<?php $this->widget('booster.widgets.TbDetailView',array(
'data'=>$model,
'type'=>'striped bordered',
'attributes'=>array(
		'title',
		'url',
		array(
			'label'=>'Category',
			'type'=>'raw',
			'value'=>$model->getRelationField("LinkCategory","title")
		),
		array(
			'label'=>'Image',
			'type'=>'raw',
			'value'=>$model->getImage()
		),
		'order',
		'time_created',
),
)); ?>