protected/models/Post.php
<?php

/**
 * This is the model class for table "post".
 *
 * The followings are the available columns in table 'post':
 * @property integer $id
 * @property integer $post_category_id
 * @property string $title
 * @property string $content
 */
class Post extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Post the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'post';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('title', 'required'),
			array('post_category_id, total_views', 'numerical', 'integerOnly'=>true),
			array('title, image', 'length', 'max'=>255),
			//array('thumbnail','file','allowEmpty'=>true,'types'=>'jpg,JPG,gif,GIF,png,PNG','maxSize'=>1024*500,'tooLarge'=>'File maksimal 500 KB','safe'=>true),
			array('image','safe'),
			array('content, tags, time_created', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, post_category_id, title, content', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'post_category'=>array(self::BELONGS_TO,'PostCategory','post_category_id')
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'post_category_id' => 'Category',
			'title' => 'Title',
			'content' => 'Content',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('post_category_id',$this->post_category_id);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('content',$this->content,true);
		
		$criteria->order = 'time_created DESC';
		
		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	
	protected function beforeDelete()
	{
		PostCategoryMap::model()->deleteAllByAttributes(array('post_id'=>$this->id));
		
		return true;
		
	}
	
	public function getTimeCreated()
	{
		return date('d-m-Y H:i:s',strtotime($this->time_created));
	}
	
	public function getImage($htmlOptions=array())
	{
		if($this->image!='')
			return CHtml::image(Yii::app()->theme->baseUrl.'/uploads/post/'.$this->image,'',$htmlOptions);
		else
			return CHtml::image(Yii::app()->theme->baseUrl.'/images/no-image.jpg','',$htmlOptions);
	}
	
	public function getDataDownload()
	{
		$model = Download::model()->findAllByAttributes(array('model'=>'Post','model_id'=>$this->id));
		
		if($model!==null)
			return $model;
		else
			return false;
	}
	
	public function countDataDownload()
	{
		return Download::model()->countByAttributes(array('model'=>'Post','model_id'=>$this->id));
	}
	
	public function getOtherPost()
	{
		$criteria = new CDbCriteria;
		$criteria->limit = 5;
		$criteria->order = 'time_created DESC';
		
		$model = Post::model()->findAll($criteria);
		
		if($model!==null)
			return $model;
		else
			return false;
	}
	
	public function getLatestPostByCategoryId($category_id=null,$limit=null)
	{
		if($limit==null)
			$limit = 3;
			
		if($category_id!=null)
		{
			$criteria = new CDbCriteria;
			$criteria->condition = 'id IN (SELECT post_id FROM post_category_map WHERE post_category_id = :category_id)';
			$criteria->params = array(':category_id'=>$category_id);
			$criteria->limit = $limit;
			$criteria->order = 'time_created DESC';
			$model = Post::model()->findAll($criteria);
			
		} else {
			$model = Post::model()->findAll(array('order'=>'time_created DESC','limit'=>$limit));
		}
		
		if($model!==null)
			return $model;
		else
			return false;
		
	}
	
	public function updatePostCategoryMap($post_category_id=null)
	{
		
		if($post_category_id == null)
		{
			foreach(PostCategoryMap::model()->findAllByAttributes(array('post_id'=>$this->id)) as $data)
			{	
				$data->active=0;
				$data->save();
			}
			
			$post_category_id = $this->post_category_id;
		}
			
		$postCategory = PostCategory::model()->findByPk($post_category_id);
		
		$parent_id = 0;
		
		if($postCategory !== null)
			$parent_id = $postCategory->parent_id;
		
		$postCategoryMap = PostCategoryMap::model()->findByAttributes(array('post_id'=>$this->id,'post_category_id'=>$post_category_id));
		
		if($postCategoryMap === null)
			$postCategoryMap = new PostCategoryMap;
		
		$postCategoryMap->post_id = $this->id;
		
		$postCategoryMap->post_category_id = $post_category_id;
		
		$postCategoryMap->active = 1;
		
		$postCategoryMap->save();
			
		if($parent_id != 0)
		{
			$this->updatePostCategoryMap($parent_id);
		}
		
		return true;
	}
	
	public function getDataPhoto()
	{
		$model = Photo::model()->findAllByAttributes(array('model'=>'Post','model_id'=>$this->id));
		
		if($model!==null)
			return $model;
		else
			return false;
	}
	
	public function countDataPhoto()
	{
		return Photo::model()->countByAttributes(array('model'=>'Post','model_id'=>$this->id));
	}
	
	public function getDataVideo()
	{
		$model = Video::model()->findAllByAttributes(array('model'=>'Post','model_id'=>$this->id));
		
		if($model!==null)
			return $model;
		else
			return false;
	}
	
	public function countDataVideo()
	{
		return Video::model()->countByAttributes(array('model'=>'Post','model_id'=>$this->id));
	}
	
	public function getExcerpt($maxLength=125) 
	{
		$str = $this->content;
		$startPos=0; 
		
		if(strlen($str) > $maxLength) 
		{
			$excerpt   = substr($str, $startPos, $maxLength-3);
			$lastSpace = strrpos($excerpt, ' ');
			$excerpt   = substr($excerpt, 0, $lastSpace);
			$excerpt  .= '...';
		} else {
			$excerpt = $str;
		}
	
		return $excerpt;
	}
	
	public function getRelationField($relation,$field)
	{
		if(!empty($this->$relation->$field))
			return $this->$relation->$field;
	}
}

protected/controllers/PostController.php
<?php

class PostController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/admin/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('read'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('index','create','update','view','chartByPostCategory',
					'removeThumbnail'
				),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('@'),
				//'expression'=>'Yii::app()->user->isAdmin()',
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	
	public function actionRead($id)
	{
		$this->layout = '//layouts/column2';
		
		$model = $this->loadModel($id);
		
		$model->total_views++;
		$model->save();
		
		$this->render('read',array(
			'model'=>$model,
		));
	}
	
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model = new Post;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			
			$image = CUploadedFile::getInstance($model,'image');
			
			if($image!==null)
				$model->image = str_replace(' ','-',time().'_'.$image->name);
			
			date_default_timezone_set('Asia/Jakarta');
			$model->time_created = date('Y-m-d H:i:s');
			
			if($model->save())
			{
				$model->updatePostCategoryMap();
				if($image!==null)
				{
					$path = Yii::app()->theme->basePath.'/uploads/post/';
					$image->saveAs($path.$model->image);
				}
				
				Yii::app()->user->setFlash('success','Data berhasil disimpan');
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}
	
	public function savePostCategory($model,$post_category_id=null)
	{
		if($post_category_id == null)
			$parent = PostCategory::model()->findByPk($model->post_category_id)->parent_id;
		else
			$parent = PostCategory::model()->findByPk($post_category_id)->parent_id;
		
		if($post_category_id == null)
			$cek = PostCategoryMap::model()->findByAttributes(array('post_id'=>$model->id,'post_category_id'=>$model->post_category_id));
		else
			$cek = PostCategoryMap::model()->findByAttributes(array('post_id'=>$model->id,'post_category_id'=>$post_category_id));
		
		if($cek === null)
			$postCategoryMap = new PostCategoryMap;
		else
			$postCategoryMap = $cek;
		
		$postCategoryMap->post_id = $model->id;
		if($post_category_id == null)
			$postCategoryMap->post_category_id = $model->post_category_id;
		else
			$postCategoryMap->post_category_id = $post_category_id;
		$postCategoryMap->active = 1;
		$postCategoryMap->save();
			
		if($parent != 0)
		{
			$postCategory = PostCategory::model()->findByPk($parent);
			$this->savePostCategory($model,$postCategory->id);
		}
	}
	
	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		
		$old_image = $model->image;
	
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			
			$model->attributes=$_POST['Post'];
			
			$image = CUploadedFile::getInstance($model,'image');
			
			if(is_object($image))
			{
				$model->image = str_replace(' ','-',time().'_'.$image->name);
				
			} else {
				$model->image = $old_image;
			}
		
			if($model->save())
			{
				$model->updatePostCategoryMap();
				if($image!==null)
				{
					$path = Yii::app()->theme->basePath.'/uploads/post/';
					$image->saveAs($path.$model->image);
					
					if(file_exists($path.$old_image) AND $old_image!='')
						unlink($path.$old_image);
				}
				
				Yii::app()->user->setFlash('success','Data berhasil disimpan');
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}
	
	public function saveUpdateCategory($model)
	{
		$postCategory = PostCategoryMap::model()->findAllByAttributes(array('post_id'=>$model->id));
		foreach($postCategory as $category)
		{
			$category->active = 0;
			$category->save();
		}
		$this->savePostCategory($model);
	}
	
	public function actionRemoveThumbnail($id)
	{
		$model = $this->loadModel($id);
		
		if($model->thumbnail != '')
		{
			$path = Yii::app()->basePath.'/../uploads/post/';
			if(file_exists($path.$model->thumbnail))
				unlink($path.$model->thumbnail);
			
			$model->thumbnail = '';
			$model->save();
			
			Yii::app()->user->setFlash('success','Thumbnail berhasil dihapus');
			$this->redirect(array('post/update','id'=>$id));
		}
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Post');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Post('search');
		
		$model->unsetAttributes();  // clear any default values
		
		if(isset($_GET['Post']))
			$model->attributes=$_GET['Post'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}
	
	public function actionChartByPostCategory()
	{
		Yii::app()->fusioncharts->setChartOptions(array(
			'caption'=>'Jumlah Post Berdasarkan Kategori', 
		));
		
		foreach(PostCategory::model()->findAll() as $data) 
		{
			Yii::app()->fusioncharts->addSet(array('label'=>$data->title, 'value'=>$data->countPost()));
		}
		
		Yii::app()->fusioncharts->getXMLData(true);
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Post::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='post-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/post/_download.php
<h3>File Unduhan</h3>
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Tambah',
		'context'=>'primary',
		'icon'=>'plus white',
		'url'=>array('/download/create','model'=>'Post','model_id'=>$model->id)
)); ?>

<div>&nbsp;</div>

<table class='table'>
<tr>
	<th style="width:8%">No</th>
	<th>Judul</th>
	<th>Total Unduh</th>
	<th>Akses</th>
	<th>Unduh</th>
	<th>Action</th>
</tr>
<?php $i=1; foreach($model->getDataDownload() as $data) { ?>
<tr>
	<td><?php print $i; ?></td>
	<td><?php print $data->title; ?></td>
	<td><?php print $data->total_download; ?></td>
	<td><?php print $data->download_access->title; ?></td>
	<td>
		<?php print CHtml::link('<i class="glyphicon glyphicon-download-alt"></i>',Yii::app()->request->baseUrl.'/uploads/download/'.$data->file,array('target'=>'_blank')); ?>
	</td>
	<td>
		<?php print CHtml::link('<i class="glyphicon glyphicon-pencil"></i>',array('download/update','id'=>$data->id)); ?>
		<?php print CHtml::link('<i class="glyphicon glyphicon-trash"></i>',array('download/hapus','id'=>$data->id),array('onclick'=>'return confirm("Yakin akan menghapus data?")')); ?>
	</td>
</tr>
<?php $i++; } ?>
</table>

protected/views/post/_form.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'id'=>'post-form',
	'enableAjaxValidation'=>false,
	'htmlOptions'=>array('enctype'=>'multipart/form-data')
)); ?>

	<p class="help-block">Kolom dengan <span class="required">*</span> harus diisi.</p>

	<?php echo $form->errorSummary($model); ?>

	
	<?php echo $form->textFieldGroup($model,'title',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->dropDownListGroup($model,'post_category_id',array(
			'widgetOptions'=>array(
				'data'=>PostCategory::model()->getParentList()
			)
	)); ?>

	<?php echo $form->ckEditorGroup($model,'content',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->ckEditorGroup($model,'excerpt',array('class'=>'span5','maxlength'=>255)); ?>
	
	
	
	<?php print $form->labelEx($model,'image'); ?>
	<?php if(!empty($model->image)) print CHtml::image(Yii::app()->request->baseUrl.'/uploads/post/'.$model->thumbnail); ?>
	<?php echo $form->fileField($model,'image',array('class'=>'span5','maxlength'=>255)); ?>
	
	<?php if(!empty($model->image)) { ?>
	<?php $this->widget('booster.widgets.TbButton',array(
			'buttonType'=>'link',
			'context'=>'danger',
			'size'=>'extra_small',
			'icon'=>'remove',
			'label'=>'',
			'url'=>array('post/removeThumbnail','id'=>$model->id)
	)); ?>
	<?php } ?>
	
	<?php print $form->error($model,'thumbnail'); ?>		
	
	<div>&nbsp;</div>

	<?php echo $form->textFieldGroup($model,'tags',array('class'=>'span5','maxlength'=>255)); ?>
	
	<div class="form-actions well">
		<?php $this->widget('booster.widgets.TbButton', array(
				'buttonType'=>'submit',
				'context'=>'primary',
				'icon'=>'ok',
				'label'=>'Simpan',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/post/_photo.php
<h3>Galeri Foto</h3>
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Tambah',
		'context'=>'primary',
		'icon'=>'plus white',
		'url'=>array('/photo/create','model'=>'Post','model_id'=>$model->id)
)); ?>

<div>&nbsp;</div>

<table class='table'>
<tr>
	<th width="8%">No</th>
	<th width="60%">Judul</th>
	<th width="20%" style="text-align:center">Foto</th>
	<th width="12%" style="text-align:center">Action</th>
</tr>
<?php $i=1; foreach($model->getDataPhoto() as $data) { ?>
<tr>
	<td><?php print $i; ?></td>
	<td><?php print $data->title; ?></td>
	<td style="text-align:center"><?php print $data->getImage(); ?></td>
	<td style="text-align:center">
		<?php print CHtml::link('<i class="glyphicon glyphicon-pencil"></i>',array('photo/update','id'=>$data->id)); ?>
		<?php print CHtml::link('<i class="glyphicon glyphicon-trash"></i>',array('photo/hapus','id'=>$data->id),array('onclick'=>'return confirm("Yakin akan menghapus data?")')); ?>
	</td>
</tr>
<?php $i++; } ?>
</table>

protected/views/post/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'post_category_id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'title',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textAreaRow($model,'content',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/post/_video.php
<h3>Galeri Video</h3>
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Tambah',
		'context'=>'primary',
		'icon'=>'plus white',
		'url'=>array('/video/create','model'=>'Post','model_id'=>$model->id)
)); ?>

<div>&nbsp;</div>

<table class='table'>
<tr>
	<th style="width:8%">No</th>
	<th width="30%">Judul</th>
	<th width="50%" style="text-align:center">Video</th>
	<th width="12%" style="text-align:center">Action</th>
</tr>
<?php $i=1; foreach($model->getDataVideo() as $data) { ?>
<tr>
	<td><?php print $i; ?></td>
	<td><?php print $data->title; ?></td>
	<td style="text-align:center"><?php print $data->displayVideo(); ?></td>
	<td style="text-align:center">
		<?php print CHtml::link('<i class="glyphicon glyphicon-pencil"></i>',array('video/update','id'=>$data->id)); ?>
		<?php print CHtml::link('<i class="glyphicon glyphicon-trash"></i>',array('video/hapus','id'=>$data->id),array('onclick'=>'return confirm("Yakin akan menghapus data?")')); ?>
	</td>
</tr>
<?php $i++; } ?>
</table>

protected/views/post/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('post_category_id')); ?>:</b>
	<?php echo CHtml::encode($data->post_category_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('title')); ?>:</b>
	<?php echo CHtml::encode($data->title); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('content')); ?>:</b>
	<?php echo CHtml::encode($data->content); ?>
	<br />


</div>

protected/views/post/admin.php
<?php $this->breadcrumbs=array(
	'Post'=>array('admin'),
	'Kelola',
); ?>

<h1>Kelola Post</h1>

<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'context'=>'primary',
		'icon'=>'plus',
		'label'=>'Tambah Post',
		'url'=>array('post/create')
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'context'=>'primary',
		'icon'=>'list',
		'label'=>'Kelola Kategori',
		'url'=>array('postCategory/admin')
)); ?>&nbsp;



<?php $this->widget('booster.widgets.TbGridView',array(
		'id'=>'post-grid',
		'dataProvider'=>$model->search(),
		'type'=>'striped bordered',
		'filter'=>$model,
		'columns'=>array(
			array(
				'header'=>'No',
				'value'=>'$this->grid->dataProvider->pagination->currentPage*$this->grid->dataProvider->pagination->pageSize+$row+1',
				'headerHtmlOptions'=>array('width'=>'5%','style'=>'text-align:center'),
				'htmlOptions'=>array('style'=>'text-align:center'),
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'title',
				'type'=>'raw',
				'value'=>'$data->title',
				'headerHtmlOptions'=>array('width'=>'40%','style'=>'text-align:center')
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'image',
				'type'=>'raw',
				'value'=>'$data->getImage(array("width"=>"180px"))',
				'headerHtmlOptions'=>array('width'=>'15%','style'=>'text-align:center')
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'post_category_id',
				'type'=>'raw',
				'value'=>'$data->getRelationField("post_category","title")',
				'filter'=>CHtml::listData(PostCategory::model()->findAll(array('order'=>'title ASC')),'id','title'),
				'headerHtmlOptions'=>array('width'=>'20%','style'=>'text-align:center'),
				'htmlOptions'=>array('style'=>'text-align:center')
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'time_created',
				'type'=>'raw',
				'value'=>'$data->getTimeCreated()',
				'headerHtmlOptions'=>array('width'=>'12%','style'=>'text-align:center'),
				'htmlOptions'=>array('style'=>'text-align:center')
			),
			array(
				'class'=>'booster.widgets.TbButtonColumn',
				'headerHtmlOptions'=>array('width'=>'8%')
			),
		),
)); ?>

protected/views/post/view.php
<?php
$this->breadcrumbs=array(
	'Kelola Post'=>array('admin'),
	$model->title,
);
?>

<h1>Lihat Post</h1>

<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Sunting',
		'context'=>'primary',
		'icon'=>'pencil white',
		'url'=>array('/post/update','id'=>$model->id)
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Baca',
		'context'=>'primary',
		'icon'=>'search white',
		'url'=>array('/post/read','id'=>$model->id),
		'htmlOptions'=>array('target'=>'_blank')
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Tambah',
		'context'=>'primary',
		'icon'=>'plus white',
		'url'=>array('/post/create')
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'label'=>'Kelola',
		'context'=>'primary',
		'icon'=>'list white',
		'url'=>array('/post/admin')
)); ?>

<div>&nbsp;</div>

<?php $this->widget('booster.widgets.TbDetailView',array(
	'data'=>$model,
	'type'=>'striped bordered',
	'attributes'=>array(
		'title',
		array(
			'label'=>'Kategori',
			'type'=>'raw',
			'value'=>$model->getRelationField("post_category","title")
		),
		array(
			'label'=>'Konten',
			'type'=>'raw',
			'value'=>$model->content
		),
		array(
			'label'=>'Image',
			'type'=>'raw',
			'value'=>$model->getImage()
		),
	),
)); ?>


<div>&nbsp;</div>

<?php $this->widget('booster.widgets.TbTabs',array(
        'type' => 'tabs', // 'tabs' or 'pills'
        'tabs' => array(
            array(
                'label' => 'Download',
                'content' => $this->renderPartial('_download',array('model'=>$model),true),
                'active' => true
            ),
			array(
                'label' => 'Photo',
                'content' => $this->renderPartial('_photo',array('model'=>$model),true),
            ),
			array(
                'label' => 'Video',
                'content' => $this->renderPartial('_video',array('model'=>$model),true),
            ),
        ),
    )
); ?>